### ISSUE TITLE
[BUG]: Flag scope "objects-interactions-fx" is not valid o

### ISSUE THREAD

**Issue by mclemente** [ZotyDev/FoundryVTT-ItemTags#1]
### Discord Username

mclemente

### Browsers

Native Foundry Client

### What Happened?

Just installed the module on my zero-module world to test things and I can't open it.
There is an issue with the _Migrate method trying to read a flag from the "objects-interactions-fx" module, which isn't present, so the scope fails.

### Reproduction Steps

```bash
1. Load the module without any other modules.
2. Try to open the Tags on an item.
3. Check console for the error.
```

### Relevant Log Output

```Shell
caught Error: undefined. Flag scope "objects-interactions-fx" is not valid or not currently active
[Detected 1 package: item-tags]
    at Item5e.getFlag (commons.js:8263:44)
    at TagHandler._Migrate (tagHandler.js:66:29)
    at TagHandler.GetTags (tagHandler.js:86:31)
    at Object.onclick (module.js:40:38)
    at HTMLAnchorElement.<anonymous> (foundry.js:5883:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

**Comment by ZotyDev** [comment]
Oops, forgot to check it! Thanks for reporting the bug, I will fix it and release a new version asap.
